### PR TITLE
UTC Time Change Fixes

### LINKED ISSUE #376: Reservation card checkin button issues
Background: "check in" button on reservation cards should only be rendered if the current day >= reservation start date.

Issue: "check in" button is unresponsive when clicked (so far only tested when the current day > reservation start date). We should take a look at this issue and do a little more testing on the validation system we have in place

### PR DESCRIPTION
**Pull request by lullofthesea**
Closes #376

Updated sorting / reservation buttons / times to match new UTC Timestamp format in database.

Tested only with 1 listing -> buttons working fine / times stored and displayed properly.

### CODE REVIEW

**Review by aidenszeto — APPROVED** [review]

File: src/components/createListing/createListing.component.js [hunk 1]
```diff
@@ -878,7 +878,7 @@ class CreateListing extends Component {
       amenities: this.state.form.amenities,
       calendarURL: this.state.form.calendarURL,
       booked: this.props.booked ? this.props.booked : [],
-      coordinates: this.state.form.location.coordinates,
+      coordinates: this.state.form.coordinates,
```
Comment (aidenszeto) [inline src/components/createListing/createListing.component.js:881]: I believe we call this `coords` instead of `coordinates` actually

**Review by aidenszeto — CHANGES_REQUESTED** [review]

**Review by aidenszeto — APPROVED** [review]

**Review by nishantbalaji — APPROVED** [review]
LGTM, could you update the precommit hook on this PR so we dont do `git add .` everytime? I updated it for the backend with the email-styling PR
