### PR TITLE
fix reservation modal bug of staying open on click off

### LINKED ISSUE #293: Reservation Popup
If I click on reservation tab, this popup:
image

shows up. Then when I click on Explore, it doesn't go away, as shown: 
image

Look at the modal on the homepage as an example

### PR DESCRIPTION
**Pull request by MikePodo**
closes #293

### CODE REVIEW

File: src/components/reservations/reservationLookupModal.component.js [hunk 1]
```diff
@@ -1,10 +1,12 @@
-import React, { useState } from "react";
+import React, { useState, useEffect } from "react";
```
Comment (aidenszeto) [inline src/components/reservations/reservationLookupModal.component.js:1]: Doesn't look like we're using useEffect so we can get rid of that import

**Review by aidenszeto — APPROVED** [review]
